default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bootstrap_app_development

test:
  <<: *default
  database: bootstrap_app_test

production:
  <<: *default
  database: bootstrap_app_production
  username: bootstrap_app
  password: <%= ENV['BOOTSTRAP_APP_DATABASE_PASSWORD'] %>
